DATA:
  DATASET: universal
  SPLIT: train_list_all_v1.txt
  IMG_SIZE: 384
MODEL:
  TYPE: swin
  NAME: swin_large_patch4_window12_384_in22k
  NUM_CLASSES: 373064
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05

  BASE_LR: 1.0e-4 # 4096 batch-size
  WARMUP_LR: 1.0e-7
  MIN_LR: 1.0e-6
  
  #BASE_LR: 1.25e-4 # 4096 batch-size
  #WARMUP_LR: 1.25e-7
  #MIN_LR: 1.25e-6